# This is a comment

<VirtualHost *:8080>
    ServerName basic-files.local
    DocumentRoot "/srv/basic-files"

    <Directory "/srv/basic-files">
        Require all granted
        Options -Indexes +FollowSymLinks
    </Directory>

    ErrorLog "${APACHE_LOG_DIR}/basic-files-error.log"
    CustomLog "${APACHE_LOG_DIR}/basic-files-access.log" combined
</VirtualHost>
