events {
    worker_connections 1024;
}

http {
    server {
        listen 8080;
        root /usr/share/nginx/html;

        location /healthz {
            access_log off;
            return 200 "ok\n";
        }
    }
}
